# Generated by Django 2.0.6 on 2018-11-25 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='calendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_time', models.TimeField(auto_now_add=True, verbose_name='event Time')),
                ('event_location', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='rabbitProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('Breed', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=6)),
                ('Age', models.CharField(max_length=10)),
                ('Size', models.CharField(max_length=10)),
                ('Spayed_Neutered', models.CharField(max_length=5)),
                ('Location', models.CharField(default='', max_length=300)),
                ('about', models.TextField()),
                ('profile_createdDate', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='rabbit_image')),
            ],
        ),
    ]
