# Generated by Django 2.0.6 on 2018-11-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit', '0002_auto_20181127_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='gunieaProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('Breed', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=6)),
                ('Age', models.CharField(max_length=10)),
                ('Size', models.CharField(max_length=10)),
                ('Spayed_Neutered', models.CharField(max_length=5)),
                ('Location', models.CharField(default='', max_length=300)),
                ('about', models.TextField()),
                ('profile_createdDate', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(max_length=400)),
            ],
        ),
    ]
